tasks:
    - name: Basic stuff
      command: |
        make install
        eval $(gp env -e)
        echo "$LANGAME_WORKER_ENV" | base64 -d > .env.production
        echo "$LANGAME_SVC_PROD" > ./svc.prod.json
        echo "$LANGAME_SVC_DEV" > ./svc.dev.json
        echo "$LANGAME_PYPIRC" | base64 -d > ./run/collection/.pypirc
        echo "$LANGAME_PIPCONF" | base64 -d > ./run/collection/pip.conf
        pip3 install yq
        echo "$LANGAME_CONFIG" | yq -y > ./config.yaml
        mkdir -p ~/kaggle
        echo "$KAGGLE_KEY" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
        export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/svc.prod.json
        gcloud beta auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS} --project=$(cat ${GOOGLE_APPLICATION_CREDENTIALS} | jq -r '.project_id')
        mkdir -p ~/.docker
        cat >~/.docker/config.json <<EOL
        {
          "credHelpers": {
            "gcr.io": "gcloud",
            "us.gcr.io": "gcloud",
            "eu.gcr.io": "gcloud",
            "asia.gcr.io": "gcloud",
            "staging-k8s.gcr.io": "gcloud",
            "marketplace.gcr.io": "gcloud"
          }
        }
        EOL
        firebase login --no-localhost
        echo "Current Google Cloud project is $(gcloud config list --format 'value(core.project)' 2>/dev/null)"

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - aaron-bond.better-comments
    - bungcip.better-toml
    - GitHub.copilot
    - gitpod.gitpod-desktop
    - googlecloudtools.cloudcode
    - hbenl.vscode-test-explorer
    - k--kato.intellij-idea-keybindings
    - littlefoxteam.vscode-python-test-adapter
    - mechatroner.rainbow-csv
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - ms-vscode-remote.remote-containers
    - ms-vscode-remote.remote-ssh
    - ms-vscode-remote.remote-ssh-edit
    - ms-vscode.test-adapter-converter
    - mushan.vscode-paste-image
    - Perkovec.emoji
    - RandomFractalsInc.vscode-data-preview
    - redhat.vscode-yaml
    - stylelint.vscode-stylelint
    - toba.vsfire
    - wix.vscode-import-cost
    - zxh404.vscode-proto3
    - 42crunch.vscode-openapi