# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/

image:
  file: .gitpod.Dockerfile