tasks:
    - name: Install dependencies
      command: |
        virtualenv env
        source env/bin/activate
        export PIP_USER=false
        pip install -e .
        pip install -r requirements-test.txt
        pip freeze
    - name: Generate service account
      command: |
        eval $(gp env -e)
        echo "$LANGAME_SVC_PROD" > notebooks/svc.prod.json
        echo "$LANGAME_SVC_DEV" > notebooks/svc.dev.json
        pip3 install yq
        echo "$LANGAME_CONFIG" | yq -y > notebooks/config.yaml
        mkdir -p ~/kaggle
        echo "$KAGGLE_KEY" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
    - name: Auth gcloud
      command: |
        gcloud auth login --no-launch-browser
        gcloud projects list
        echo "gcloud config set project [PROJECT_ID]"
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - aaron-bond.better-comments
    - bungcip.better-toml
    - GitHub.copilot
    - gitpod.gitpod-desktop
    - googlecloudtools.cloudcode
    - hbenl.vscode-test-explorer
    - k--kato.intellij-idea-keybindings
    - littlefoxteam.vscode-python-test-adapter
    - mechatroner.rainbow-csv
    - ms-azuretools.vscode-docker
    - ms-kubernetes-tools.vscode-kubernetes-tools
    - ms-python.python
    - ms-python.vscode-pylance
    - ms-toolsai.jupyter
    - ms-vscode-remote.remote-containers
    - ms-vscode-remote.remote-ssh
    - ms-vscode-remote.remote-ssh-edit
    - ms-vscode.test-adapter-converter
    - mushan.vscode-paste-image
    - Perkovec.emoji
    - RandomFractalsInc.vscode-data-preview
    - redhat.vscode-yaml
    - stylelint.vscode-stylelint
    - toba.vsfire
    - wix.vscode-import-cost
    - zxh404.vscode-proto3