apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: langame-worker
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containers:
        - image: langame-worker
