# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='langame.socialis',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tapi.proto\x12\x10langame.socialis\"@\n\x11\x41\x64\x64PlayersRequest\x12\x0e\n\x04text\x18\x01 \x01(\tH\x00\x12\x10\n\x06speech\x18\x02 \x01(\x0cH\x00\x42\t\n\x07players\"\'\n\x16ValidatePlayersRequest\x12\r\n\x05valid\x18\x01 \x01(\x08\"@\n\x04Game\x12\x0c\n\x04text\x18\x01 \x01(\t\x12*\n\x05state\x18\x02 \x01(\x0e\x32\x1b.langame.socialis.GameState*0\n\tGameState\x12\x0e\n\nPLAYER_ADD\x10\x00\x12\x13\n\x0fPLAYER_VALIDATE\x10\x01\x32\xaa\x01\n\x08Socialis\x12I\n\nAddPlayers\x12#.langame.socialis.AddPlayersRequest\x1a\x16.langame.socialis.Game\x12S\n\x0fValidatePlayers\x12(.langame.socialis.ValidatePlayersRequest\x1a\x16.langame.socialis.Gameb\x06proto3'
)

_GAMESTATE = _descriptor.EnumDescriptor(
  name='GameState',
  full_name='langame.socialis.GameState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PLAYER_ADD', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PLAYER_VALIDATE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=204,
  serialized_end=252,
)
_sym_db.RegisterEnumDescriptor(_GAMESTATE)

GameState = enum_type_wrapper.EnumTypeWrapper(_GAMESTATE)
PLAYER_ADD = 0
PLAYER_VALIDATE = 1



_ADDPLAYERSREQUEST = _descriptor.Descriptor(
  name='AddPlayersRequest',
  full_name='langame.socialis.AddPlayersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='langame.socialis.AddPlayersRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speech', full_name='langame.socialis.AddPlayersRequest.speech', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='players', full_name='langame.socialis.AddPlayersRequest.players',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=31,
  serialized_end=95,
)


_VALIDATEPLAYERSREQUEST = _descriptor.Descriptor(
  name='ValidatePlayersRequest',
  full_name='langame.socialis.ValidatePlayersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='valid', full_name='langame.socialis.ValidatePlayersRequest.valid', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=136,
)


_GAME = _descriptor.Descriptor(
  name='Game',
  full_name='langame.socialis.Game',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='langame.socialis.Game.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='langame.socialis.Game.state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=202,
)

_ADDPLAYERSREQUEST.oneofs_by_name['players'].fields.append(
  _ADDPLAYERSREQUEST.fields_by_name['text'])
_ADDPLAYERSREQUEST.fields_by_name['text'].containing_oneof = _ADDPLAYERSREQUEST.oneofs_by_name['players']
_ADDPLAYERSREQUEST.oneofs_by_name['players'].fields.append(
  _ADDPLAYERSREQUEST.fields_by_name['speech'])
_ADDPLAYERSREQUEST.fields_by_name['speech'].containing_oneof = _ADDPLAYERSREQUEST.oneofs_by_name['players']
_GAME.fields_by_name['state'].enum_type = _GAMESTATE
DESCRIPTOR.message_types_by_name['AddPlayersRequest'] = _ADDPLAYERSREQUEST
DESCRIPTOR.message_types_by_name['ValidatePlayersRequest'] = _VALIDATEPLAYERSREQUEST
DESCRIPTOR.message_types_by_name['Game'] = _GAME
DESCRIPTOR.enum_types_by_name['GameState'] = _GAMESTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddPlayersRequest = _reflection.GeneratedProtocolMessageType('AddPlayersRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDPLAYERSREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:langame.socialis.AddPlayersRequest)
  })
_sym_db.RegisterMessage(AddPlayersRequest)

ValidatePlayersRequest = _reflection.GeneratedProtocolMessageType('ValidatePlayersRequest', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATEPLAYERSREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:langame.socialis.ValidatePlayersRequest)
  })
_sym_db.RegisterMessage(ValidatePlayersRequest)

Game = _reflection.GeneratedProtocolMessageType('Game', (_message.Message,), {
  'DESCRIPTOR' : _GAME,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:langame.socialis.Game)
  })
_sym_db.RegisterMessage(Game)



_SOCIALIS = _descriptor.ServiceDescriptor(
  name='Socialis',
  full_name='langame.socialis.Socialis',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=255,
  serialized_end=425,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddPlayers',
    full_name='langame.socialis.Socialis.AddPlayers',
    index=0,
    containing_service=None,
    input_type=_ADDPLAYERSREQUEST,
    output_type=_GAME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ValidatePlayers',
    full_name='langame.socialis.Socialis.ValidatePlayers',
    index=1,
    containing_service=None,
    input_type=_VALIDATEPLAYERSREQUEST,
    output_type=_GAME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SOCIALIS)

DESCRIPTOR.services_by_name['Socialis'] = _SOCIALIS

# @@protoc_insertion_point(module_scope)
