# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import api_pb2 as api__pb2


class SocialisStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddPlayers = channel.unary_unary(
                '/langame.socialis.Socialis/AddPlayers',
                request_serializer=api__pb2.AddPlayersRequest.SerializeToString,
                response_deserializer=api__pb2.Game.FromString,
                )
        self.ValidatePlayers = channel.unary_unary(
                '/langame.socialis.Socialis/ValidatePlayers',
                request_serializer=api__pb2.ValidatePlayersRequest.SerializeToString,
                response_deserializer=api__pb2.Game.FromString,
                )


class SocialisServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddPlayers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidatePlayers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SocialisServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddPlayers': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPlayers,
                    request_deserializer=api__pb2.AddPlayersRequest.FromString,
                    response_serializer=api__pb2.Game.SerializeToString,
            ),
            'ValidatePlayers': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidatePlayers,
                    request_deserializer=api__pb2.ValidatePlayersRequest.FromString,
                    response_serializer=api__pb2.Game.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'langame.socialis.Socialis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Socialis(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddPlayers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/langame.socialis.Socialis/AddPlayers',
            api__pb2.AddPlayersRequest.SerializeToString,
            api__pb2.Game.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ValidatePlayers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/langame.socialis.Socialis/ValidatePlayers',
            api__pb2.ValidatePlayersRequest.SerializeToString,
            api__pb2.Game.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
