apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: collection
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: "true"
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "100"
    spec:
      containerConcurrency: 5
      containers:
        image: gcr.io/langame-86ac4/collection:1.2.3
        ports:
          - containerPort: 8080
            name: http1
        env:
          - name: SENTRY_RELEASE
            value: "1.2.3"
          - name: ENVIRONMENT
            value: "production"
        resources:
          limits:
            cpu: "4"
            memory: 8192Mi
      timeoutSeconds: 1200
