apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    cloud.googleapis.com/location: europe-west3
  name: collection
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      containers:
        image: gcr.io/langame-86ac4/collection:1.0.1
        ports:
          - containerPort: 8080
            name: http1
        env:
          - name: GET_MEMES_URL
            value: "https://us-central1-langame-86ac4.cloudfunctions.net/getMemes"
        resources:
          limits:
            cpu: "4"
            memory: 8192Mi
      timeoutSeconds: 1200
      